//@version=4

// Works well on BTC 4h

strategy("EMA - RSI Strategy")

rsi = rsi(close, 14)
shortSMA = sma(rsi, 10)
longSMA = sma(rsi, 50)

longCondition = crossover(shortSMA, longSMA)
shortCondition = crossunder(shortSMA, longSMA)

if (longCondition)
    strategy.entry("long", strategy.long, 100, comment="BUY", when = rsi > 50)

if (shortCondition)
    strategy.entry("short", strategy.short, 100, comment="SELL", when = rsi < 50)

// Print indicators
plot(rsi, "RSI", color=color.purple)
plot(shortSMA, "shortSMA", color=color.orange)
plot(longSMA, "longSMA", color=color.blue)
